### ISSUE TITLE
Problem building with meson - cblas not found

### ISSUE THREAD

**Issue by RomitChakraborty** [dftd4/cpp-d4#1]
Can't seem to get meson configured to find cblas for the setup.
I get the following error:
meson.build:30:2: ERROR: Dependency "cblas" not found, tried pkgconfig, framework and cmake
A detailed log is attached.
Thanks for your help!
[meson-log.txt](https://github.com/dftd4/cpp-d4/files/4247734/meson-log.txt)

**Comment by awvwgk** [comment]
Have you made sure the `cblas.h` is in the include path?

**Comment by RomitChakraborty** [comment]
Hi Sebastian,

Thanks a bunch for getting back!
I wish it were as straightforward as adding cblas.h to the include path. It
took a while but was finally able to compile with dependency set to
'openblas' instead of 'cblas'.  Please do let me know if you can think of a
more easily replicable solution. Thanks for your help!

best,
romit

*Romit Chakraborty*
*Postdoc*

*Martin Head-Gordon Group*

*University of California, Berkeley, and, *
*Lawrence Berkeley National Lab *

**Comment by awvwgk** [comment]
I tested this program with netlib LAPACK, BLAS and the LAPACKE, CBLAS development libraries installed, since it was originally implemented in a QM code which came with its own wrappers for the LA backend, I just needed some replacement.

**Comment by RomitChakraborty** [comment]
Thanks for writing back. So this particular c++ port couts the d4
dispersion energy, and not just the ATM term?
How does one go about implementing gradients and Hessians. Thanks again!

**Comment by RomitChakraborty** [comment]
Addendum:
Are the coordinates input in bohrs or angstroms?

**Comment by awvwgk** [comment]
@RomitChakraborty Is this still an issue?

**Comment by RomitChakraborty** [comment]
Hi Sebastian,

Do you mean dependencies or the Bohr to Angstrom conversion?
Dependencies I could fix by installing openblas which has both cblas and
lapacke. As for the conversion factor: was able to get the same result to
1e-10 a.u accuracy for a test set of molecules via function calls (with a
cmake build we worked on at Q-Chem) and via a standalone version of the
dft-d4 fortran code. The c++ API was very helpful!
We did note that the conversion factor you use in your code is slightly
different from the one used internally in Q-Chem.

best,
romit

*Romit Chakraborty*
*Postdoc*

*Martin Head-Gordon Group*

*University of California, Berkeley, and, *
*Lawrence Berkeley National Lab *

**Comment by awvwgk** [comment]
Okay, thanks for info. Sounds like I can close this issue.
